### ISSUE TITLE
Since Firefox 53 not works

### ISSUE THREAD

**Issue by Endor8** [nickolay/infolister#25]
Not works since Firefox 53. Please fix.
Possible reason:
NS_ERROR_XPC_JSOBJECT_HAS_NO_FUNCTION_NAMED: Component returned failure code: 0x80570030 (NS_ERROR_XPC_JSOBJECT_HAS_NO_FUNCTION_NAMED) [nsIWebNavigation.loadURI]

caused from this line in the file infolister.js:
frame.webNavigation.loadURI("about:info", 0, null, null, null);

Above mentioned infos came from here: 
https://www.camp-firefox.de/forum/viewtopic.php?p=1035026#p1035026

I hope this helps.
Cheers
Endor

**Comment by nickolay** [comment]
Thanks for the notice. I'm not maintaining InfoLister anymore, but this was a relatively easy fix (see 160b8c9). I put up http://nickolay.github.io/infolister/infolister-0.10.5a3.xpi but didn't test it at all.

**Comment by Endor8** [comment]
Hi thank you for the fast fix. But since this version is not signed it is not possible
to install it.  Will you sign it?

**Comment by nickolay** [comment]
Now that you mention it, something changed in AMO to allow signing the addon without getting through the review process. I uploaded the signed version to the same location - http://nickolay.github.io/infolister/infolister-0.10.5a3.xpi

**Comment by Endor8** [comment]
Wow that was fast. Thank you very much.
Everything seems to work perfect now.
Thank you again.
Cheers
Endor
